#++ Packages
#--- Preset CRAN Mirror
options(repos = c(CRAN = "https://cloud.r-project.org/"))

#--- Install any requisite packags
# install.packages("package")
# install.packages(c("matrixStats", "GSA", "shiny", "openxlsx", "Rcpp"))
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("impute")
# install_github("cran/samr")
# install.packages("samr")
# install.packages("ggrepel")
# install.packages("plsRglm")
# install.packages("ggfortify")
# install.packages("FactoMineR")
# install.packages("mice")
# install.packages("factoextra")
# install.packages("cowplot")
# install.packages("httpgd")
# install.packages("languageserver")
# install.packages("discriMiner")
# install.packages("caret")
# install.packages("pls")
# install.packages("randomForest")
# install.packages("glmnet")
# install.packages("stats")
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("mixOmics")
# devtools::install_github("rubenarslan/rcamisc")
#install.packages("rgl")
#--- Load any requisite packags
library(BiocManager)
library(matrixStats)
library(GSA)
library(openxlsx)
library(Rcpp)
library(eNetXplorer)
library(lme4)
library(jtools)
library(dplyr)
library(tibble)
library(glmmLasso)
library(MASS)
library(nlme)
library(ggplot2)
library(gtsummary)
library(broom)
library(tidyr)
library(purrr)
library(devtools)
library(shiny)
library(readr)
library(ggrepel)
library(ggfortify)
library(FactoMineR)
library(mice)
library(factoextra)
library(cowplot)
library(httpgd)
library(languageserver)
library(discriMiner)
library(caret)
library(pls)
library(mixOmics)
library(randomForest)
library(glmnet)
library(stats)
library(httpgd)
library(rcamisc)
library(plsRglm)
library(rcamisc)
library(rgl)
#--- Detecting package conflicts with 'amigoingmad'
#_This will ensure dplyr is always "on top" for functions like select()
amigoingmad()
}
